name: Snyk package scan

on:
  pull_request:
    branches: [ "main" ]
  push:

jobs:
  Checkov:
    runs-on: ubuntu-latest
    # defaults:
    #   run:
    #     working-directory: terraform

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Snyk steup
      uses: snyk/actions/setup@master

    - name: Snyk monitor
      run: snyk iac test
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      working-directory: terraform
